# Generated by Django 4.2.7 on 2023-12-17 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=50, verbose_name='Prénom')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('dte_naissance', models.DateField(verbose_name='Date de Naissance')),
                ('creation_dte', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('image', models.ImageField(upload_to='Adherents', verbose_name='Image')),
                ('adresse', models.CharField(max_length=700, verbose_name='Adresse')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('mail', models.EmailField(max_length=654, verbose_name='E-Mail')),
                ('tel', models.CharField(max_length=10, verbose_name='Téléphone')),
                ('acte_naissance', models.ImageField(upload_to='Adherents_acte', verbose_name='Acte de Naissance')),
                ('save_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
            options={
                'verbose_name': 'Adherent',
                'verbose_name_plural': 'Adherents',
            },
        ),
    ]
