# Generated by Django 4.2.7 on 2023-12-17 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Decipline')),
                ('jour', models.CharField(max_length=150, verbose_name='Jour')),
                ('prix', models.FloatField(verbose_name='Prix')),
            ],
            options={
                'verbose_name': 'Sport',
                'verbose_name_plural': 'Sports',
            },
        ),
        migrations.AlterField(
            model_name='adherent',
            name='acte_naissance',
            field=models.ImageField(blank=True, null=True, upload_to='Adherents_acte', verbose_name='Acte de Naissance'),
        ),
        migrations.AlterField(
            model_name='adherent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Adherents', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='adherent',
            name='mail',
            field=models.EmailField(blank=True, max_length=654, null=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='adherent',
            name='save_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adherentuser', to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.CreateModel(
            name='Abonement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateField(verbose_name='Date Debut')),
                ('expiration', models.DateField(verbose_name='Expiration')),
                ('prix', models.FloatField(verbose_name='Prix')),
                ('adhrent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonementadherent', to='sport.adherent')),
                ('sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonementsport', to='sport.sport')),
            ],
            options={
                'verbose_name': 'Abonement',
                'verbose_name_plural': 'Abonements',
            },
        ),
    ]
