# Generated by Django 4.2.7 on 2023-12-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_adherent_etat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adherent',
            name='etat',
        ),
    ]
