# Generated by Django 4.2.7 on 2023-12-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0004_remove_adherent_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='cin',
            field=models.ImageField(blank=True, null=True, upload_to='Adherents_cin', verbose_name='CIN'),
        ),
        migrations.AlterField(
            model_name='adherent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Adherents_image', verbose_name='Image'),
        ),
    ]
