# Generated by Django 4.2.7 on 2023-12-27 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sport', '0005_adherent_cin_alter_adherent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.sport', verbose_name='Sport'),
        ),
        migrations.AlterField(
            model_name='adherent',
            name='save_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adherentuser', to=settings.AUTH_USER_MODEL, verbose_name='Createur'),
        ),
    ]
