# Generated by Django 4.2.7 on 2023-12-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0006_adherent_sport_alter_adherent_save_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='payement',
            field=models.BooleanField(default=True),
        ),
    ]
